name: General Issue
description: Use this template for reporting bugs, proposing enhancements, or improving documentation.
title: "📝 Issue: "
labels: []
assignees: []

body:
  - type: input
    id: title
    attributes:
      label: Issue Title
      description: Provide a concise and descriptive title for this issue.
      placeholder: e.g., Improve Navigation Responsiveness on Mobile
    validations:
      required: true

  - type: input
    id: files
    attributes:
      label: Affected File(s)
      description: Indicate the relevant file paths or directories associated with this issue.
      placeholder: e.g., src/components/Navbar.tsx, styles/global.css

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clearly describe the issue in detail. Explain what is missing, incorrect, or needs improvement.
      placeholder: e.g., The navigation bar layout breaks on smaller screens and overlaps with page content.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Outline the expected outcome or behavior once the issue is resolved.
      placeholder: e.g., The navigation bar should remain fully responsive and accessible across all device sizes.

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Provide actionable steps or recommendations for addressing this issue.
      placeholder: |
        - Refactor CSS to ensure responsive breakpoints.
        - Test layout on common mobile viewports.
        - Validate accessibility and interaction flow.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Indicate the urgency or importance level of this issue.
      options:
        - Low
        - Medium
        - High
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: Select the most appropriate category for this issue.
      options:
        - Bug
        - Enhancement
        - Documentation
        - Design
        - Refactor
        - Other
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Provide any extra context, references, or relevant information.
      placeholder: e.g., Refer to similar implementation in Footer component for layout consistency.
